name: "StockWise"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/home/app
    command: nodemon server.js

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
