spring.application.name=demo

spring.datasource.url=jdbc:mysql://database-1.cl20moqok5cy.ap-south-1.rds.amazonaws.com/my_db
spring.datasource.username=admin
spring.datasource.password=9rz0Sd4peMEpIUkH8Ahd
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jap.hibernate.ddl-auto=update
spring.jap.show-sql=true
