apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-deployment
  labels:
    name: service-b-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
        - image: embarkx/tax-service-b:latest
          name: service-b
          imagePullPolicy: Always

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: 4000
              name: service-b-port
