kind: Service
apiVersion: v1
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 31000
